schema_version = "1.0.0"

blender_version_min = "4.2.0"
id = "popoti_align_helper"
license = ["SPDX:GPL-3.0-or-later", ]
maintainer = "AIGODLIKE Community(小萌新)"
name = "POPOTI Align Helper"
tagline = "More friendly alignment based on observation perspective"
type = "add-on"
version = "1.2.5"
tags = ["3D View", "Object"]
